### PR TITLE
Handle resolution reduction

### PR DESCRIPTION
**Pull request by aftabsikander**
Fixed issue #69 and #49

### CODE REVIEW

**Comment by gnumarcelo** [comment]
Hi guys, any change we get this merged?

**Comment by luiskenny3000** [comment]
Hi, when will have a new version with this fix?

**Comment by ShreyashPromact** [comment]
Any updates on this?
I have checked, still, Image resolution is not getting changed to given one.

**Comment by aftabsikander** [comment]
@ShreyashPromact  I am not sure when this fix will be merged, However, you can check my forked version.

**Comment by Aracem** [comment]
To resolve the size bug the solution on this issue comment resolves better the problem
https://github.com/zetbaitsu/Compressor/issues/86#issuecomment-354242855

The image size is wrong because this ''calculateInSampleSize'' method has a bug with the first iteration of the bucle.

**Comment by marchrius** [comment]
Is this fix compatible with image rotation? At the moment I have a stretched rotated image with switched h and w

**Comment by DISKONEKTeD** [comment]
is this project abandoned?

**Pull request merged**
